// POST /api/auth/register - Register a new user

import { NextRequest, NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { db, generateId } from "@/lib/db";
import { signToken } from "@/lib/auth";
import { User } from "@/lib/types";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { name, email, password } = body;

    // Validate input
    if (!name || typeof name !== "string" || name.trim().length < 2) {
      return NextResponse.json(
        { error: "Name must be at least 2 characters" },
        { status: 400 }
      );
    }

    if (!email || typeof email !== "string" || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json(
        { error: "Valid email is required" },
        { status: 400 }
      );
    }

    if (!password || typeof password !== "string" || password.length < 6) {
      return NextResponse.json(
        { error: "Password must be at least 6 characters" },
        { status: 400 }
      );
    }

    // Check if user already exists
    const existingUser = await db.getUserByEmail(email.toLowerCase());
    if (existingUser) {
      return NextResponse.json(
        { error: "Email already registered" },
        { status: 409 }
      );
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 12);

    // Create user
    const user: User = {
      id: generateId(),
      User_id: "", // Will be auto-generated by database
      name: name.trim(),
      email: email.toLowerCase(),
      password: hashedPassword,
      createdAt: new Date().toISOString(),
    };

    // Create user in database and get the actual created user (with DB ID and UUID)
    console.log("Attempting to create user in DB:", { ...user, password: "[REDACTED]" });
    const createdUser = await db.createUser(user);

    // Generate JWT token with the REAL database ID
    const token = await signToken({ userId: createdUser.id, email: createdUser.email });

    return NextResponse.json(
      {
        token,
        user: {
          id: createdUser.id,
          User_id: createdUser.User_id,
          name: createdUser.name,
          email: createdUser.email,
          createdAt: createdUser.createdAt,
        },
      },
      { status: 201 }
    );
  } catch (error: any) {
    console.error("Register error details:", {
      message: error.message,
      stack: error.stack,
      code: error.code,
      meta: error.meta,
    });
    return NextResponse.json(
      { error: "Internal server error", details: error.message },
      { status: 500 }
    );
  }
}
